### PR TITLE
Added TypeScript definition

### PR DESCRIPTION
**Pull request by Xiot**
Created a TypeScript definition file to go along with angular-toastr.
I didn't include the dependent definitions for angular or jQuery though

### CODE REVIEW

**Comment by Foxandxss** [comment]
@Xiot Hey mate, lot of time later, not even sure if you're still using this lib. I know more about all this typescript and definitelytyped stuff and I am interested of adding this. I made some changes on the library so maybe it needs a rebase.

If you don't have time or you're not even using the project, don't worry, I will learn more about how to create this files and update it myself.

**Comment by Xiot** [comment]
Hey @Foxandxss, I haven't used this library in a while. I don't have time right now to go through and make the changes myself, but feel free to take what I submitted as a start.  You can also ask me any questions you like to clear things up if you need to.

**Comment by tzarger** [comment]
@Xiot @Foxandxss Has any progress been made on this? If not, I might be interested in adding some missing functionality from the d.ts file proposed above... Please let me know.

**Comment by Foxandxss** [comment]
Be my guest, open a new PR with it and I merge it.

**Comment by tzarger** [comment]
@Foxandxss  Alright, thanks. Will get a new PR when I finish.

**Comment by macnibblet** [comment]
Any update on it ?

**Comment by Foxandxss** [comment]
Doesn't seems like so.

Anyway, I want to do a complete rewrite for 2.0.0 using ES6 so I guess it would potentially break a definition.

**Comment by Foxandxss** [comment]
I am closing this PR because the change is too old and the library changed quite a bit.

The idea is to wait until I do a 2.0.0 release and then see if I can do a definition file or someone else creates a PR.

**Comment by SimeonC** [comment]
Hey, don't have time to create a PR but I've copied what I'm using into a GIST here: https://gist.github.com/SimeonC/7a91d8198a3148e53c23 - it's based off the work here and the readme.

**Pull request closed without merging**
