### PR TITLE
onTap callback

### PR DESCRIPTION
**Pull request by mrzepinski**

### CODE REVIEW

**Comment by Foxandxss** [comment]
What is the purpose of this? `onHidden` receives a boolean to wether the toast is closed via click or not.

**Comment by mrzepinski** [comment]
@Foxandxss I would like to make toast sticky (tapToDismiss = false), set custom action on click (onTap) and close toast when close button is clicked.

**Comment by Foxandxss** [comment]
I get the idea now. What is the use case? I mean what are you trying to do? I am curious.

If I were to merge this PR, you need to rebase it to current master (there are some weird changes in there that shouldn't be there) and also not running `gulp production` (AKA not including dist, just the changes on source).

**Comment by mrzepinski** [comment]
@Foxandxss Ok. I will close this PR. I figured out that I have to pass $event to close function when stopPropagation needs to be called.

I want to set onTap function which shows modal to user when toast is clicked. My toast needs to be sticky, until user click on close btn.

**Pull request closed without merging**
