### PR TITLE
created scss file

### PR DESCRIPTION
**Pull request by bubbleheadinc**
There is a .less file, but I prefer .scss. I created a .scss file with additional variables for increased style flexibility without having to override compiled css styles. 

The file includes `!default` flags so each var can be overridden in a separate project .scss partial. Added a breakpoint mixin to make responsive more flexible.

Default flag example:
 `toastr.scss` file
```
...
$toast-color-success: #51a351 !default;
...
```

Override variables in your own project .scss file and import partial before `toastr.scss`
'_project-partial.scss`
```
...
$toast-color-success: magenta;
...
```

Compiled css will generate styles with partial var changes without overrides.

Hope this helps some folks!

### CODE REVIEW

**Comment by Foxandxss** [comment]
I am not really really sure about this. I can see your purpose, but I am not a CSS guy and to be honest, the `less` file I have is a copy & paste from the original `toastr` one (plus some angular animations).

If I merge this, I will gonna need to apply those changes by hand and also translate them to scss.

On the other hand, I want to get rid of `replace: true` on the directives but the actual `less` file is a bit tight on the toast markup.

So I can see a change to SCSS if apart from this goodies, I can remove `replace: true` and have the toasts styled correctly.

**Comment by bubbleheadinc** [comment]
Not sure what you mean about `replace: true`. What does `replace: true` have to do with a `scss` version of the styles?

You mean you would have to translate the changes to the `less` file (not `scss` as you wrote) to keep them consistent?

I only expanded the `scss` file from the `less` file already in the repo and it just makes it more flexible to style the current toast structure when using Sass.

**Comment by Foxandxss** [comment]
It has nothing to do. The thing is, that I am not really sure I want to
simply swap the less to scss, mostly because having it in less, makes me
easier to update it from the original repo.

But, but, I need to make some changes on the less file by myself to be able
to remove `replace: true`, so a scss file with what you did + the needed
markup to make the directive work without replace, that would be really
good.

**Comment by bubbleheadinc** [comment]
Ah ok. Gotcha. So you could have both `less` and `sass` like the original toastr repo? As an aside, I'm hopeful devs start putting `scss` and `less` files in distribution builds and not just compiled `css` so they can be used as partials in a project build. I'm sure people would argue with me on that.

**Comment by Foxandxss** [comment]
This is not final yet, but perhaps for 2.0.0 I would rewrite the entire CSS by hand (to remove the replace) and I would do that with SASS.

Closing this.

**Pull request closed without merging**
