### PR TITLE
Adding a "refresh timer" to the scope

### PR DESCRIPTION
**Pull request by jcford73**
Adding a method to restart the timeout timer to keep a toast visible longer.

### CODE REVIEW

**Comment by Foxandxss** [comment]
A toast is an alert, to say something, for me, it doesn't make sense to restart the timer.

If an user needs to read it, they can hover it so it doesn't go away.

**Comment by jcford73** [comment]
My use case is uploading multiple files. Instead of opening a screen full of toasts to announce that each uploaded successfully, I'm showing one toast and if it's still visible when the next file finishes, I'm updating the message and resetting the timer.

**Comment by Foxandxss** [comment]
I get you. I will think about that.

**Comment by jcford73** [comment]
Do you know of any other way to accomplish what I'm trying? Currently, the toast continues to update until it times out and then another one immediately pops up with a new timer. It works okay, but the flicker when it has to pop a new toast is just a bit ugly.

**Comment by Foxandxss** [comment]
I would make a permanent toast for the time being and after all upload finishes, kill the toast.

**Comment by jcford73** [comment]
Yes that would sort of work. Except then if there were only a few small files, the toast would disappear too quickly.

**Comment by Foxandxss** [comment]
I want this option, but having a method in the current scope is just one step, To access it you need to `myToast.scope.refreshTimer()` and I don't really like that API.

Also, I need tests.

**Comment by jcford73** [comment]
I agree about having to go through the scope property to refresh the timer.

To be consistent with the rest of the API, it should probably go through the service like `toastr.refreshTimer(toast)` unless you want a shorter method name. Maybe `toastr.extend(toast)`? Or `toastr.prolong(toast)`?

**Comment by Foxandxss** [comment]
Perhaps just "restart"?

**Comment by jcford73** [comment]
Could that give the impression it affects more than just the timer?

**Comment by Foxandxss** [comment]
You are right. Then `refreshTimeout` or simply `refresh` ?

**Comment by jcford73** [comment]
I'll just keep refreshTimeout for maximum clarity.

Another topic: Tests are in toastr_spec.js but I haven't figured out how to run them locally.

**Comment by Foxandxss** [comment]
For the tests, you need to run testem. I need to swap that for karma.

So for today:

```
$ npm install -g testem
$ testem -f config/testem.json
```

The tests will watch any change that comes from `$ gulp`.

**Comment by Foxandxss** [comment]
Nice work on that, but we would need a few more tests cases where the toast is not there (long gone) and one where the toast was just gone one millisecond ago.

**Comment by jcford73** [comment]
Will do.

**Comment by jcford73** [comment]
Are the tests sufficient? Are there any other test cases needed?

**Comment by Foxandxss** [comment]
Probably yes. Will double check tomorrow and release this weekend :)

**Comment by Foxandxss** [comment]
Thanks, I merged this. I will make a release.

**Pull request closed without merging**
