### PR TITLE
Added a count() api

### PR DESCRIPTION
**Pull request by timbell**
Added a count() public api to return the current number of toasts.

### CODE REVIEW

**Comment by Foxandxss** [comment]
What is the use case?

**Comment by timbell** [comment]
I keep a history of all alerts with the ability to show/hide them on request.
Show alerts => clear current toasts (if any) then create toasts for all alertsHide alerts => clear current toastsClear alerts => clear current toasts and alerts history 
Show alerts: active/visible if alerts.length > 0Hide alerts: active/visible if toasts.length > 0Clear alerts: active/visible if alerts.length > 0
I need toastr.count() to properly activate/show the "Hide alerts" option
Tim

Date: Fri, 20 Nov 2015 07:42:33 -0800

**Comment by Foxandxss** [comment]
I am thinking that it is something that should be done in userland. You have a very concrete usage of toasts, and I think that you can keep your own registry of toasts and that registry could give you the length of toasts you have.

I will give this a thought and see if it could be helpful in here or not.

**Comment by timbell** [comment]
I could keep a registry of toasts etc. but that seems pretty expensive and a little error prone. I think a count() api is a pretty innocent addition and might help others too.But your call, obviously :-)
Date: Fri, 20 Nov 2015 07:55:49 -0800

**Comment by Foxandxss** [comment]
Yeah, not a big deal.

Write tests for it and I merge it.

**Comment by Foxandxss** [comment]
I don't like your tests to be honest (I wouldn't create that matcher) but don't worry. Will fix that myself and merge it tomorrow.

**Comment by Foxandxss** [comment]
I renamed it to `active` and I merged it.

**Pull request closed without merging**
