### PR TITLE
feat: auto dismiss the last maxOpened toasts

### LINKED ISSUE #76: Auto-dismiss when limit is set
Given:

```js
angular.extend(toastrConfig, {
  maxOpened: 1
});
```

… I would expect the newest toast to be shown regardless of timeout. Put another way, after opening a toast, subsequent toasts should auto-dismiss the last toast.

### PR DESCRIPTION
**Pull request by tlvince**
For example, when `maxOpened: 1`, always show the newest toast regardless of
timeouts.

Closes #76.

### CODE REVIEW

**Comment by Foxandxss** [comment]
Who said anything about a perfect PR? It was perfect in all the ways.

Thank you very much.

**Comment by tlvince** [comment]
Great! Could you tag a new release?

**Comment by Foxandxss** [comment]
I want to close some issues first.

**Comment by Foxandxss** [comment]
Release is up.

**Pull request closed without merging**
