### PR TITLE
Wrap container target in a jqLite object

### PR DESCRIPTION
**Pull request by luckycadow**
Get the target container as a jqLite object so it can be passed into $animate.enter()

### CODE REVIEW

**Comment by Foxandxss** [comment]
Thank you, but I would need a test case of it failing with the fix so I can see how it fails.

**Comment by luckycadow** [comment]
I took a look at the tests and because the $animate service is mocked, it will never fail as it doesn't do anything with the parameters it's given.  I'm not familiar with the test framework, but if there's anything else you'd like me to do let me know.

**Comment by Foxandxss** [comment]
I see, but even when animate is a mock, it will use its methods. If you were able to create a plunker http://plnkr.co/edit/tpl:nKLNBdve51sqOoKZAOUS, loading in there angular-toastr and creating a reproducible error, I could take a look.

The current issue I have is that my tests are not failing and the demo I have in my playground is not failing also so I need to know under what conditions it is failing so I can try and then review your patch.

**Comment by luckycadow** [comment]
When plunkr is working again I'll send you link.  I have one right now that it just won't let me save, but all you have to do is attempt to use the latest version of angular-toastr.  The mock $animate service doesn't do anything with the objects passed in, but if you look at the angular source you can see it calls .prepend() on the second parameter to $animate.enter() which assumes it's a jqLite object.

**Comment by luckycadow** [comment]
I got a plunk to save.  The first call to any toastr method throws an exception of 'undefined is not a function', subsequent calls do nothing.  http://plnkr.co/edit/Xb5KmQ0gLcST6nhJ4fhW

**Comment by Foxandxss** [comment]
I see, thank you. I will check it better tomorrow and release a fix.

**Comment by Foxandxss** [comment]
I merged it. What I was missing was the fact that it failed without ngAnimate.

**Pull request closed without merging**
