### PR TITLE
Require styles for Webpack

### PR DESCRIPTION
**Pull request by leandroz**
Require css file so Webpack can process it.

### CODE REVIEW

**Comment by Foxandxss** [comment]
I will think about this.

I want to rewrite this library and generate an UMD webpack file so I am not sure what I will do with the CSS. I don't want to include the `.css` automatically for one version and then for the next one decide I don't want to automatically include it.

**Comment by leandroz** [comment]
I think that the styles are part of the library and should be included as default. Maybe adding a config to not include them, but I bet that in the 99% of the cases people want the CSS too.

**Comment by Foxandxss** [comment]
Yeah, they want the CSS too, that for sure.

My point is that I am going to rewrite this library (to ES6) and output an UMD module and I don't want to create a new version with your PR and then realize afterwards that I need to do something else for the next version with the rewrite.

So I need to research a bit and think and see what is the best solution.

In the mean time, requiring the css by hand works.

**Comment by Foxandxss** [comment]
After talking with several people, they think that I should leave this as is. Better to have it separate.

**Pull request closed without merging**
